os:
  - linux
  - osx

language: c++

compiler:
    - gcc

env:
  - BUILD_CXX_LIB=ON BUILD_NODEJS_LIB=OFF BUILD_PYTHON_LIB=OFF
  - BUILD_CXX_LIB=OFF BUILD_NODEJS_LIB=ON BUILD_PYTHON_LIB=OFF
  - BUILD_CXX_LIB=OFF BUILD_NODEJS_LIB=OFF BUILD_PYTHON_LIB=ON
  - BUILD_CXX_LIB=ON BUILD_NODEJS_LIB=OFF BUILD_PYTHON_LIB=OFF PYTHONV=2
  - BUILD_CXX_LIB=ON BUILD_NODEJS_LIB=OFF BUILD_PYTHON_LIB=OFF PYTHONV=3

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      if [[ "$PYTHONV" == "2" ]]; then
        brew install boost-python;
      else
        brew install python boost-python@3;
      fi;
      export PYTHON_LIBRARY=$(python-config --prefix)/lib/libpython2.7.dylib;
      export PYTHON_INCLUDE_DIR=$(python-config --prefix)/include/python2.7;
      export CMAKE_FIND_FRAMEWORK=LAST;
      export CMAKE_VERBOSE_MAKEFILE=ON;
    else
      sudo apt-get update;
      sudo apt-get install -y git libboost-python-dev libboost-system-dev;
    fi
before_script:
  - if [[ "$BUILD_NODEJS_LIB" == "ON" ]]; then npm install; fi
  - mkdir build
  - cd build
  - cmake -DBUILD_CXX_LIB=${BUILD_CXX_LIB} -DBUILD_NODEJS_LIB=${BUILD_NODEJS_LIB} -DBUILD_PYTHON_LIB=${BUILD_PYTHON_LIB} -DPYTHON_LIBRARY=${PYTHON_LIBRARY} -DPYTHON_INCLUDE_DIR=${PYTHON_INCLUDE_DIR} ../src
script: 
  - make

after_success:
  - sudo make install
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then otool -L /usr/local/lib/python2.7/site-packages/ocl.so; fi
