os:
  - linux
  - osx

language: c++

compiler:
  - gcc

jobs:
  - name: "Python 2"
    before_install:
      - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get update; fi
      - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get install -y git; fi
      - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python@2 boost-python; else sudo apt-get install -y libboost-python-dev; fi
      - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get install -y libboost-system-dev; fi
    before_script:
      - mkdir build
      - cd build
      - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake ../src -DPYTHON_LIBRARY=$(python-config --prefix)/lib/libpython2.7.dylib -DPYTHON_INCLUDE_DIR=$(python-config --prefix)/include/python2.7 -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev; else cmake ../src; fi
    script:
      - make
    after_success:
      - sudo make install
      - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then otool -L /usr/local/lib/python2.7/site-packages/ocl.so; fi
  - name: "Python 3"
    before_install:
      - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get update; fi
      - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get install -y git; fi
      - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python boost-python3; else sudo apt-get install -y libboost-python-dev; fi
      - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get install -y libboost-system-dev; fi
    before_script:
      - mkdir build
      - cd build
      - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake ../src -DBUILD_CXX_LIB=OFF -DBUILD_PYTHON_LIB=ON -BUILD_NODEJS_LIB=OFF -DPYTHON_LIBRARY=$(python-config --prefix)/lib/libpython2.7.dylib -DPYTHON_INCLUDE_DIR=$(python-config --prefix)/include/python2.7 -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev; else cmake ../src -DBUILD_CXX_LIB=OFF -DBUILD_PYTHON_LIB=ON -BUILD_NODEJS_LIB=OFF; fi
    script:
      - make
    after_success:
      - sudo make install
      - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then otool -L /usr/local/lib/python2.7/site-packages/ocl.so; fi
  - name: "C++"
    before_install:
      - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get install -y libboost-system-dev; fi
    before_script:
      - mkdir build
      - cd build
      - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake ../src -DBUILD_CXX_LIB=ON -DBUILD_PYTHON_LIB=OFF -BUILD_NODEJS_LIB=OFF -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev; else cmake ../src -DBUILD_CXX_LIB=ON -DBUILD_PYTHON_LIB=OFF -BUILD_NODEJS_LIB=OFF; fi
    script:
      - make
  - name: "Node.js"
    before_install:
      - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get install -y libboost-system-dev; fi
    before_script:
      - npm install
      - mkdir build
      - cd build
      - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake ../src -DBUILD_CXX_LIB=OFF -DBUILD_PYTHON_LIB=OFF -BUILD_NODEJS_LIB=ON -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev; else cmake ../src -DBUILD_CXX_LIB=OFF -DBUILD_PYTHON_LIB=OFF -BUILD_NODEJS_LIB=ON; fi
    script:
      - make