name: Test

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop
      - feat/experiments
    tags:
      - v*

jobs:
  cxx:
    name: ${{ matrix.os_short }} c++
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-2022", "macos-15", "ubuntu-22.04"]
        include:
          - os: "windows-2022"
            os_short: "windows"
          - os: "macos-15"
            os_short: "macos"
          - os: "ubuntu-22.04"
            os_short: "linux"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache Boost on windows only
        id: cache-boost
        if: ${{ matrix.os_short == 'windows' }}
        uses: actions/cache@v4
        with:
          key: boost-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt') }}
          path: |
            /c/Program Files (x86)/Boost
      - name: Build Boost windows
        if: ${{ matrix.os_short == 'windows' && steps.cache-boost.outputs.cache-hit != 'true' }}
        shell: bash
        run: |
          curl -L -O https://github.com/boostorg/boost/releases/download/boost-1.87.0/boost-1.87.0-cmake.tar.gz
          tar -xzf boost-1.87.0-cmake.tar.gz
          cd boost-1.87.0
          cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_CONFIGURATION_TYPES=Release -D BOOST_INCLUDE_LIBRARIES="math;foreach;graph" -S . -B build
          cmake --build build --config Release --parallel 4
          cmake --install build --config Release --prefix "/c/Program Files (x86)/Boost"
      - name: Install deps linux
        if: ${{ matrix.os_short == 'linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libomp-dev libboost-dev
      - name: Install deps macos
        if: ${{ matrix.os_short == 'macos' }}
        run: |
          brew install libomp boost
      - name: Build
        shell: bash
        run: |
          mkdir -p lib/ocl
          cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_CONFIGURATION_TYPES=Release -D BUILD_CXX_LIB="ON" -S . -B build
          cmake --build build --config Release --parallel 4
          cmake --install build --config Release --prefix $(pwd)/lib/ocl --verbose
      - name: Test
        shell: bash
        run: |
          cd examples/cpp/test
          cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_CONFIGURATION_TYPES=Release -D CMAKE_PREFIX_PATH="$(pwd)/../../../lib/ocl" -S . -B build
          cmake --build build --config Release --parallel 4
          cd ./build
          ./test_example
  # nodejs:
  #   name: ${{ matrix.os_short }} node.js
  #   runs-on: ${{ matrix.os }}
  #   timeout-minutes: 120
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os: ["windows-2022", "macos-15", "ubuntu-22.04"]
  #       include:
  #         - os: "windows-2022"
  #           os_short: "windows"
  #           libdir: windows-nodejs-x64
  #         - os: "macos-15"
  #           os_short: "macos"
  #           libdir: macos-nodejs-x64
  #         - os: "ubuntu-22.04"
  #           os_short: "linux"
  #           libdir: linux-nodejs-x64
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - name: Install
  #       shell: bash
  #       run: |
  #         if [ "${{ matrix.os_short }}" == "linux" ]; then
  #           export OCL_SUDO_INSTALL="1"
  #         fi
  #         ./install.sh \
  #           --install-ci-deps \
  #           --build-library nodejs \
  #           --build-type release \
  #           --node-architecture x64 \
  #           --install-boost \
  #           --boost-prefix $(pwd) \
  #           --install \
  #           --install-prefix $(pwd)/src/npmpackage/build/Release/${{ matrix.libdir }} \
  #           --test
  python:
    name: ${{ matrix.os_short }} python
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-2022", "macos-15", "ubuntu-22.04"]
        include:
          - os: "windows-2022"
            os_short: "windows"
            python_version: "3.10"
          - os: "macos-15"
            os_short: "macos"
            python_version: "3.13"
          - os: "ubuntu-22.04"
            os_short: "linux"
            python_version: "3.10"
            cmake_generator: "Unix Makefiles"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache Boost Python on windows only
        id: cache-boost-python
        if: ${{ matrix.os_short == 'windows' }}
        uses: actions/cache@v4
        with:
          key: boost-python-${{ runner.os }}-${{ hashFiles('**/CMakeLists.txt') }}
          path: |
            /c/Program Files (x86)/Boost
      - name: Python venv
        shell: bash
        run: |
          python -m venv venv
      - name: Build Boost windows
        shell: bash
        if: ${{ matrix.os_short == 'windows' && steps.cache-boost-python.outputs.cache-hit != 'true' }}
        run: |
          source venv/Scripts/activate
          curl -L -O https://github.com/boostorg/boost/releases/download/boost-1.87.0/boost-1.87.0-cmake.tar.gz
          tar -xzf boost-1.87.0-cmake.tar.gz
          cd boost-1.87.0
          cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_CONFIGURATION_TYPES=Release -D BOOST_INCLUDE_LIBRARIES="python;math;foreach;graph" -D BOOST_ENABLE_PYTHON="ON" -S . -B build
          cmake --build build --config Release --parallel 4
          cmake --install build --config Release --prefix "/c/Program Files (x86)/Boost"
      - name: Install deps linux
        if: ${{ matrix.os_short == 'linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libomp-dev libboost-dev libboost-python-dev
      - name: Install deps macos
        if: ${{ matrix.os_short == 'macos' }}
        run: |
          brew install python3 libomp boost-python3
      - name: Install Dumpbin
        if: ${{ matrix.os_short == 'windows' }}
        uses: lorenalexm/install-dumpbin-action@main
      - name: Build
        shell: bash
        run: |
          if [ "${{ matrix.os_short }}" == "windows" ]; then
            source venv/Scripts/activate
          else
            source venv/bin/activate
          fi
          cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_CONFIGURATION_TYPES=Release -D BUILD_PY_LIB=ON -S . -B build
          cmake --build build --config Release --parallel 4
          cmake --install build --config Release --verbose
          if [ "${{ matrix.os_short }}" == "windows" ]; then
            ls -lah venv/lib/site-packages/opencamlib
            dumpbin /exports venv/lib/site-packages/opencamlib/ocl.pyd
          fi
      - name: Test
        shell: bash
        run: |
          if [ "${{ matrix.os_short }}" == "windows" ]; then
            source venv/Scripts/activate
          else
            source venv/bin/activate
          fi
          cd examples/python
          python test.py
